// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250129123348_seedVillaToDb")]
    partial class seedVillaToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<Guid>("VillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VillaCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VillaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillaImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaOccupancy")
                        .HasColumnType("int");

                    b.Property<double>("VillaPrice")
                        .HasColumnType("float");

                    b.Property<int>("VillaSizeInSquareFeet")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VillaUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaId");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            VillaId = new Guid("18198d77-55fb-4d9a-b14d-e8f9f3f6fa28"),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaImageUrl = "https://placehold.co/600x400",
                            VillaName = "Royal Villa",
                            VillaOccupancy = 4,
                            VillaPrice = 200.0,
                            VillaSizeInSquareFeet = 550
                        },
                        new
                        {
                            VillaId = new Guid("3a0ba39a-21c1-4f88-8a41-cad14d244f2c"),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaImageUrl = "https://placehold.co/600x401",
                            VillaName = "Premium Pool Villa",
                            VillaOccupancy = 4,
                            VillaPrice = 300.0,
                            VillaSizeInSquareFeet = 550
                        },
                        new
                        {
                            VillaId = new Guid("83698710-a57a-4c23-bb22-bee22a86a173"),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaImageUrl = "https://placehold.co/600x402",
                            VillaName = "Luxury Pool Villa",
                            VillaOccupancy = 4,
                            VillaPrice = 400.0,
                            VillaSizeInSquareFeet = 750
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
