// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250128182029_AddVillasTableToDb")]
    partial class AddVillasTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<Guid>("VillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VillaCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VillaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillaImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaOccupancy")
                        .HasColumnType("int");

                    b.Property<double>("VillaPrice")
                        .HasColumnType("float");

                    b.Property<int>("VillaSizeInSquareFeet")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VillaUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaId");

                    b.ToTable("Villas");
                });
#pragma warning restore 612, 618
        }
    }
}
